id: IE0AB7438
initial_creation_type: ebook
source_metadata:
  id: RDI-SK-05
  title: ནི་གུ་ཆོས་དྲུག་གི་ཟིན་ཁྲིད་གཅེས་བཏུས།
  author: མཛད་པ་པོ། ཏཱ་ར་ནཱ་ཐ།
  authors: &id001
  - མཛད་པ་པོ། ཏཱ་ར་ནཱ་ཐ།
  sku: RDI-SK-05
  cover: RDI-SK-05.jpeg
  volume: {}
  series: ཤངས་པའི་རྣལ་འབྱོར་ཐེམ་སྐས་གདམས་ངག་ཕྱོགས་བསྒྲིགས།
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: ནི་གུ་ཆོས་དྲུག་གི་ཟིན་ཁྲིད་གཅེས་བཏུས།
  authors: *id001
  sku: RDI-SK-05
  cover: RDI-SK-05.jpeg
layers:
- Author
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Footnote
- Sabche
- Yigchung
